// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type AgentTaskRepository interface {
	Create(ctx context.Context, userID uuid.UUID, agentTask *models.AgentTask) (*models.AgentTask, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.AgentTask, error)
	FindByID(ctx context.Context, userID uuid.UUID, agentTaskID uuid.UUID) (*models.AgentTask, error)
	Update(ctx context.Context, userID uuid.UUID, agentTask *models.AgentTask) (*models.AgentTask, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, agentTaskID uuid.UUID, agentTask *models.AgentTask, fields *AgentTaskUpdateFields) (*models.AgentTask, error)
	Delete(ctx context.Context, userID uuid.UUID, agentTaskID uuid.UUID) error
}

type AgentTaskUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewAgentTaskUpdateFields() *AgentTaskUpdateFields {
	return &AgentTaskUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *AgentTaskUpdateFields) Name() *AgentTaskUpdateFields {
	return f.add("name")
}

func (f *AgentTaskUpdateFields) Instruction() *AgentTaskUpdateFields {
	return f.add("instruction")
}

func (f *AgentTaskUpdateFields) KDIDs() *AgentTaskUpdateFields {
	return f.add("kd_ids")
}

func (f *AgentTaskUpdateFields) TriggerType() *AgentTaskUpdateFields {
	return f.add("trigger_type")
}

func (f *AgentTaskUpdateFields) TriggerTime() *AgentTaskUpdateFields {
	return f.add("trigger_time")
}

func (f *AgentTaskUpdateFields) TriggerWeekday() *AgentTaskUpdateFields {
	return f.add("trigger_weekday")
}

func (f *AgentTaskUpdateFields) TriggerIntervalHours() *AgentTaskUpdateFields {
	return f.add("trigger_interval_hours")
}

func (f *AgentTaskUpdateFields) Enabled() *AgentTaskUpdateFields {
	return f.add("enabled")
}

func (f *AgentTaskUpdateFields) NotifyEnabled() *AgentTaskUpdateFields {
	return f.add("notify_enabled")
}

func (f *AgentTaskUpdateFields) LastRunAt() *AgentTaskUpdateFields {
	return f.add("last_run_at")
}

func (f *AgentTaskUpdateFields) LastStatus() *AgentTaskUpdateFields {
	return f.add("last_status")
}

func (f *AgentTaskUpdateFields) NextRunAt() *AgentTaskUpdateFields {
	return f.add("next_run_at")
}

func (f *AgentTaskUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *AgentTaskUpdateFields) add(column string) *AgentTaskUpdateFields {
	if f == nil {
		f = NewAgentTaskUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
