// Code generated by codegen; DO NOT EDIT.

package repository

import (
	"context"
	"github.com/boxify/api-go/internal/models"
	"github.com/google/uuid"
)

type SkillRepository interface {
	Create(ctx context.Context, userID uuid.UUID, skill *models.Skill) (*models.Skill, error)
	List(ctx context.Context, userID uuid.UUID) ([]*models.Skill, error)
	FindByID(ctx context.Context, userID uuid.UUID, skillID uuid.UUID) (*models.Skill, error)
	Update(ctx context.Context, userID uuid.UUID, skill *models.Skill) (*models.Skill, error)
	UpdateFields(ctx context.Context, userID uuid.UUID, skillID uuid.UUID, skill *models.Skill, fields *SkillUpdateFields) (*models.Skill, error)
	Delete(ctx context.Context, userID uuid.UUID, skillID uuid.UUID) error
}

type SkillUpdateFields struct {
	columns []string
	seen    map[string]struct{}
}

func NewSkillUpdateFields() *SkillUpdateFields {
	return &SkillUpdateFields{
		seen: map[string]struct{}{},
	}
}

func (f *SkillUpdateFields) Name() *SkillUpdateFields {
	return f.add("name")
}

func (f *SkillUpdateFields) Description() *SkillUpdateFields {
	return f.add("description")
}

func (f *SkillUpdateFields) Icon() *SkillUpdateFields {
	return f.add("icon")
}

func (f *SkillUpdateFields) Prompt() *SkillUpdateFields {
	return f.add("prompt")
}

func (f *SkillUpdateFields) ToolKeys() *SkillUpdateFields {
	return f.add("tool_keys")
}

func (f *SkillUpdateFields) KBID() *SkillUpdateFields {
	return f.add("kb_id")
}

func (f *SkillUpdateFields) Config() *SkillUpdateFields {
	return f.add("config")
}

func (f *SkillUpdateFields) Enabled() *SkillUpdateFields {
	return f.add("enabled")
}

func (f *SkillUpdateFields) IsBuiltin() *SkillUpdateFields {
	return f.add("is_builtin")
}

func (f *SkillUpdateFields) Sort() *SkillUpdateFields {
	return f.add("sort")
}

func (f *SkillUpdateFields) Columns() []string {
	if f == nil || len(f.columns) == 0 {
		return nil
	}
	out := make([]string, len(f.columns))
	copy(out, f.columns)
	return out
}

func (f *SkillUpdateFields) add(column string) *SkillUpdateFields {
	if f == nil {
		f = NewSkillUpdateFields()
	}
	if f.seen == nil {
		f.seen = map[string]struct{}{}
	}
	if _, ok := f.seen[column]; ok {
		return f
	}
	f.seen[column] = struct{}{}
	f.columns = append(f.columns, column)
	return f
}
