// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type SkillRepository struct {
	db *gorm.DB
}

func NewSkillRepository(db *gorm.DB) repository.SkillRepository {
	return &SkillRepository{db: db}
}

func (r *SkillRepository) Create(ctx context.Context, userID uuid.UUID, skill *models.Skill) (*models.Skill, error) {
	skill.UserID = userID
	if err := r.db.WithContext(ctx).Create(skill).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建技能失败")
	}
	return skill, nil
}

func (r *SkillRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.Skill, error) {
	var rows []*models.Skill

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询技能列表失败")
	}

	return rows, nil
}

func (r *SkillRepository) FindByID(ctx context.Context, userID uuid.UUID, skillID uuid.UUID) (*models.Skill, error) {
	skill := &models.Skill{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", skillID, userID).
		First(skill).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("技能不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询技能失败")
	}
	return skill, nil
}

func (r *SkillRepository) Update(ctx context.Context, userID uuid.UUID, skill *models.Skill) (*models.Skill, error) {
	result := r.db.WithContext(ctx).
		Model(&models.Skill{}).
		Where("id = ? AND user_id = ?", skill.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(skill)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新技能失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("技能不存在")
	}
	return r.FindByID(ctx, userID, skill.ID)
}

func (r *SkillRepository) UpdateFields(ctx context.Context, userID uuid.UUID, skillID uuid.UUID, skill *models.Skill, fields *repository.SkillUpdateFields) (*models.Skill, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.Skill{}).
		Where("id = ? AND user_id = ?", skillID, userID).
		Select(columns).
		Updates(skill)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新技能失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("技能不存在")
	}
	return r.FindByID(ctx, userID, skillID)
}

func (r *SkillRepository) Delete(ctx context.Context, userID uuid.UUID, skillID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", skillID, userID).
		Delete(&models.Skill{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除技能失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("技能不存在")
	}
	return nil
}
