// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type AgentPersonaRepository struct {
	db *gorm.DB
}

func NewAgentPersonaRepository(db *gorm.DB) repository.AgentPersonaRepository {
	return &AgentPersonaRepository{db: db}
}

func (r *AgentPersonaRepository) Create(ctx context.Context, userID uuid.UUID, agentPersona *models.AgentPersona) (*models.AgentPersona, error) {
	agentPersona.UserID = userID
	if err := r.db.WithContext(ctx).Create(agentPersona).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建智能体人格失败")
	}
	return agentPersona, nil
}

func (r *AgentPersonaRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.AgentPersona, error) {
	var rows []*models.AgentPersona

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体人格列表失败")
	}

	return rows, nil
}

func (r *AgentPersonaRepository) FindByID(ctx context.Context, userID uuid.UUID, agentPersonaID uuid.UUID) (*models.AgentPersona, error) {
	agentPersona := &models.AgentPersona{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", agentPersonaID, userID).
		First(agentPersona).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("智能体人格不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体人格失败")
	}
	return agentPersona, nil
}

func (r *AgentPersonaRepository) Update(ctx context.Context, userID uuid.UUID, agentPersona *models.AgentPersona) (*models.AgentPersona, error) {
	result := r.db.WithContext(ctx).
		Model(&models.AgentPersona{}).
		Where("id = ? AND user_id = ?", agentPersona.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(agentPersona)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新智能体人格失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("智能体人格不存在")
	}
	return r.FindByID(ctx, userID, agentPersona.ID)
}

func (r *AgentPersonaRepository) UpdateFields(ctx context.Context, userID uuid.UUID, agentPersonaID uuid.UUID, agentPersona *models.AgentPersona, fields *repository.AgentPersonaUpdateFields) (*models.AgentPersona, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.AgentPersona{}).
		Where("id = ? AND user_id = ?", agentPersonaID, userID).
		Select(columns).
		Updates(agentPersona)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新智能体人格失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("智能体人格不存在")
	}
	return r.FindByID(ctx, userID, agentPersonaID)
}

func (r *AgentPersonaRepository) Delete(ctx context.Context, userID uuid.UUID, agentPersonaID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", agentPersonaID, userID).
		Delete(&models.AgentPersona{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除智能体人格失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("智能体人格不存在")
	}
	return nil
}
