// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type AgentConfigRepository struct {
	db *gorm.DB
}

func NewAgentConfigRepository(db *gorm.DB) repository.AgentConfigRepository {
	return &AgentConfigRepository{db: db}
}

func (r *AgentConfigRepository) Create(ctx context.Context, userID uuid.UUID, agentConfig *models.AgentConfig) (*models.AgentConfig, error) {
	agentConfig.UserID = userID
	if err := r.db.WithContext(ctx).Create(agentConfig).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建智能体配置失败")
	}
	return agentConfig, nil
}

func (r *AgentConfigRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.AgentConfig, error) {
	var rows []*models.AgentConfig

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体配置列表失败")
	}

	return rows, nil
}

func (r *AgentConfigRepository) FindByID(ctx context.Context, userID uuid.UUID, agentConfigID uuid.UUID) (*models.AgentConfig, error) {
	agentConfig := &models.AgentConfig{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", agentConfigID, userID).
		First(agentConfig).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("智能体配置不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体配置失败")
	}
	return agentConfig, nil
}

func (r *AgentConfigRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*models.AgentConfig, error) {
	agentConfig := &models.AgentConfig{}
	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		First(agentConfig).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("智能体配置不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体配置失败")
	}
	return agentConfig, nil
}

func (r *AgentConfigRepository) Update(ctx context.Context, userID uuid.UUID, agentConfig *models.AgentConfig) (*models.AgentConfig, error) {
	result := r.db.WithContext(ctx).
		Model(&models.AgentConfig{}).
		Where("id = ? AND user_id = ?", agentConfig.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(agentConfig)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新智能体配置失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("智能体配置不存在")
	}
	return r.FindByID(ctx, userID, agentConfig.ID)
}

func (r *AgentConfigRepository) UpdateFields(ctx context.Context, userID uuid.UUID, agentConfigID uuid.UUID, agentConfig *models.AgentConfig, fields *repository.AgentConfigUpdateFields) (*models.AgentConfig, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.AgentConfig{}).
		Where("id = ? AND user_id = ?", agentConfigID, userID).
		Select(columns).
		Updates(agentConfig)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新智能体配置失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("智能体配置不存在")
	}
	return r.FindByID(ctx, userID, agentConfigID)
}

func (r *AgentConfigRepository) Delete(ctx context.Context, userID uuid.UUID, agentConfigID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", agentConfigID, userID).
		Delete(&models.AgentConfig{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除智能体配置失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("智能体配置不存在")
	}
	return nil
}
