// Code generated by codegen; DO NOT EDIT.

package postgres

import (
	"context"
	"errors"
	"github.com/boxify/api-go/internal/models"
	"github.com/boxify/api-go/internal/repository"
	"github.com/boxify/api-go/internal/xerr"
	"github.com/google/uuid"
	"gorm.io/gorm"
)

type AgentTaskRepository struct {
	db *gorm.DB
}

func NewAgentTaskRepository(db *gorm.DB) repository.AgentTaskRepository {
	return &AgentTaskRepository{db: db}
}

func (r *AgentTaskRepository) Create(ctx context.Context, userID uuid.UUID, agentTask *models.AgentTask) (*models.AgentTask, error) {
	agentTask.UserID = userID
	if err := r.db.WithContext(ctx).Create(agentTask).Error; err != nil {
		return nil, xerr.Wrapf(err, "创建智能体任务失败")
	}
	return agentTask, nil
}

func (r *AgentTaskRepository) List(ctx context.Context, userID uuid.UUID) ([]*models.AgentTask, error) {
	var rows []*models.AgentTask

	err := r.db.WithContext(ctx).
		Where("user_id = ?", userID).
		Order("updated_at DESC").
		Find(&rows).Error
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体任务列表失败")
	}

	return rows, nil
}

func (r *AgentTaskRepository) FindByID(ctx context.Context, userID uuid.UUID, agentTaskID uuid.UUID) (*models.AgentTask, error) {
	agentTask := &models.AgentTask{}
	err := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", agentTaskID, userID).
		First(agentTask).Error
	if errors.Is(err, gorm.ErrRecordNotFound) {
		return nil, xerr.NotFound("智能体任务不存在")
	}
	if err != nil {
		return nil, xerr.Wrapf(err, "查询智能体任务失败")
	}
	return agentTask, nil
}

func (r *AgentTaskRepository) Update(ctx context.Context, userID uuid.UUID, agentTask *models.AgentTask) (*models.AgentTask, error) {
	result := r.db.WithContext(ctx).
		Model(&models.AgentTask{}).
		Where("id = ? AND user_id = ?", agentTask.ID, userID).
		Omit("id", "user_id", "user", "created_at", "updated_at").
		Updates(agentTask)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新智能体任务失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("智能体任务不存在")
	}
	return r.FindByID(ctx, userID, agentTask.ID)
}

func (r *AgentTaskRepository) UpdateFields(ctx context.Context, userID uuid.UUID, agentTaskID uuid.UUID, agentTask *models.AgentTask, fields *repository.AgentTaskUpdateFields) (*models.AgentTask, error) {
	columns := fields.Columns()
	if len(columns) == 0 {
		return nil, xerr.BadRequest("更新字段不能为空")
	}
	result := r.db.WithContext(ctx).
		Model(&models.AgentTask{}).
		Where("id = ? AND user_id = ?", agentTaskID, userID).
		Select(columns).
		Updates(agentTask)
	if result.Error != nil {
		return nil, xerr.Wrapf(result.Error, "更新智能体任务失败")
	}
	if result.RowsAffected == 0 {
		return nil, xerr.NotFound("智能体任务不存在")
	}
	return r.FindByID(ctx, userID, agentTaskID)
}

func (r *AgentTaskRepository) Delete(ctx context.Context, userID uuid.UUID, agentTaskID uuid.UUID) error {
	result := r.db.WithContext(ctx).
		Where("id = ? AND user_id = ?", agentTaskID, userID).
		Delete(&models.AgentTask{})
	if result.Error != nil {
		return xerr.Wrapf(result.Error, "删除智能体任务失败")
	}
	if result.RowsAffected == 0 {
		return xerr.NotFound("智能体任务不存在")
	}
	return nil
}
